# Generated by Django 4.2.3 on 2023-07-19 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_usuario_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='fecha_nacimiento',
        ),
    ]
