# Generated by Django 4.2.3 on 2023-07-27 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_usuario_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=200)),
                ('nombre_solicitante', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=15)),
                ('rubro_proveedor', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=200)),
                ('comentario', models.CharField(max_length=500)),
            ],
        ),
    ]
